package com.foresight.task.domain;

public enum TaskActivityType {
    CREATED,
    DETAILS_UPDATED,
    STATUS_CHANGED,
    ASSIGNEE_CHANGED,
    PRIORITY_CHANGED,
    DUE_DATE_CHANGED,
    ESTIMATE_CHANGED,
    PROGRESS_UPDATED,
    DEPENDENCY_ADDED,
    DEPENDENCY_REMOVED,
    ARCHIVED,
    UNASSIGNED_BY_MEMBERSHIP_CHANGE
}
